# How to use
# ==========
# $ python mesonet/chan_lab/event_analyzer_app.py --config mesonet/chan_lab/configs/event_analyzer_app.yaml
#
# Arguments
# =========
# - plots: A list of dictionaries. Each item in the list corresponds to a
#   separate plot in the app. Each dictionary specifies a "type" of plot as well
#   as arguments ("args") describing that plot. See the docs/yaml_to_py.md for
#   more on the available types and arguments.
# - plot_rows: The number of rows to use to plot the data in the app.
#
# Outputs
# =======
# None

# full4 dataset
plots:
- {
  type: "video",
  args: {
    filename: "/Users/christian/Documents/summer2023/matlab/my_data/full4/fc2_save_2023-08-08-111558-0000.avi",
    event_frames: [205, 3805, 7405, 11005, 14605, 18206, 21806, 25406],
    title: "Pupil"
  }
}
- {
  type: "video",
  args: {
    filename: "/Users/christian/Documents/summer2023/matlab/my_data/full4/fc2_save_2023-08-08-111557-0000.avi",
    event_frames: [234, 3837, 7441, 11044, 14648, 18251, 21855, 25458],
    title: "Body"
  }
}
- {
  type: "image",
  args: {
    filename: "/Users/christian/Documents/summer2023/matlab/my_data/full4/02_awake_8x8_30hz_28000fr_FR30Hz_BPF1-5Hz_GSR_DFF0-G4-fr1-28000.raw",
    event_frames: [160, 3755, 7351, 10946, 14541, 18137, 21732, 25327],
    title: "Mesoscale",
    image_width: 128,
    image_height: 128,
    kwargs: {},
    region_points: "/Users/christian/Documents/summer2023/MesoNet/mesonet_outputs/full4_atlas_brain/dlc_output/region_points_7.pkl"
  }
}
- {
  type: "pupillometry",
  args: {
    filename: "/Users/christian/Documents/summer2023/pupillometry_matlab/example_full4/clean.mat",
    event_frames: [205, 3805, 7405, 11005, 14605, 18206, 21806, 25406],
    title: "Pupillometry"
  }
}
plot_rows: 2

# full5 dataset
# plots:
# - {
#   type: "video",
#   args: {
#     filename: "/Users/christian/Documents/summer2023/matlab/my_data/full5/fc2_save_2023-08-09-103031-0000.avi",
#     event_frames: [272, 3872, 7472, 11072, 14672, 18272, 21872, 25472],
#     title: "Pupil"
#   }
# }
# - {
#   type: "video",
#   args: {
#     filename: "/Users/christian/Documents/summer2023/matlab/my_data/full5/fc2_save_2023-08-09-103033-0000.avi",
#     event_frames: [225, 3828, 7432, 11035, 14639, 18242, 21846, 25449],
#     title: "Body"
#   }
# }
# - {
#   type: "image",
#   args: {
#     filename: "/Users/christian/Documents/summer2023/matlab/my_data/full5/02_awake_8x8_30hz_28000fr_FR30Hz_BPF1-5Hz_GSR_DFF0-G4-fr1-28000.raw",
#     event_frames: [156, 3751, 7346, 10942, 14537, 18132, 21728, 25323],
#     title: "Mesoscale",
#     image_width: 128,
#     image_height: 128,
#     kwargs: {},
#     region_points: "/Users/christian/Documents/summer2023/MesoNet/mesonet_outputs/full5_atlas_brain/dlc_output/region_points_3.pkl"
#   }
# }
# - {
#   type: "pupillometry",
#   args: {
#     filename: "/Users/christian/Documents/summer2023/pupillometry_matlab/example_full5/clean.mat",
#     event_frames: [272, 3872, 7472, 11072, 14672, 18272, 21872, 25472],
#     title: "Pupillometry"
#   }
# }
# plot_rows: 2
