pupil_event_frames: [
  313,
  3916,
  7520,
  11123,
  14727,
  18330,
  21912,
  25515,
  29119,
  32722,
]
mesoscale_event_start_frame: 88
pupil_file: "/Users/christian/Downloads/fc2_save_2023-02-09-135224-0000.avi"
mesoscale_file: "/Users/christian/Documents/summer2023/matlab/my_data/flash1/02_awake_8x8_30hz_36500fr_FR30Hz_BPF1-5Hz_GSR_DFF0-G4-fr1-36480_FR30Hz_BPF1-5Hz_GSR_DFF0-G4-fr1-36480.raw"
pupillometry_file: "/Users/christian/Documents/summer2023/pupillometry_matlab/example_flash1/fc2_save_2023-02-09-135224-0000Pupil Radii.csv"
save_dir: "/Users/christian/Documents/summer2023/MesoNet/data_events/test/"
frames_before: -20
frames_after: 20
plot_rows: 4
