mesoscale_file: "/Users/christian/Documents/summer2023/matlab/my_data/isoflurane1_mouse6_eye-r/imMean.mat"
region_points_file: "/Users/christian/Documents/summer2023/MesoNet/mesonet_outputs/isoflurane1_mouse6_eye-r_atlas_brain/dlc_output/region_points.pkl"
save_dir: "/Users/christian/Documents/summer2023/MesoNet/data/isoflurane1_mouse6_eye-r"
event_frame: 29
fps: 30.0
scope: 1.5
